version: "3"

services:
  fishjam:
    image: "ghcr.io/fishjam-cloud/fishjam:0.10.0-dev"
    container_name: fishjam
    restart: on-failure
    platform: linux/amd64
    healthcheck:
      test: >
        curl --fail -H "authorization: Bearer development" http://localhost:5002/room || exit 1
      interval: 3s
      retries: 2
      timeout: 2s
      start_period: 30s
    environment:
      FJ_PORT: 5003
      FJ_HOST: "localhost:5003"
      FJ_WEBRTC_TURN_IP: "${EXTERNAL_IP:-127.0.0.1}"
      FJ_WEBRTC_TURN_LISTEN_IP: "0.0.0.0"
      FJ_WEBRTC_TURN_PORT_RANGE: "50000-50050"
      FJ_WEBRTC_TURN_TCP_PORT: "49999"
      FJ_SERVER_API_TOKEN: "development"
      FJ_CHECK_ORIGIN: "false"
    ports:
      - "5003:5003"
      - "49999:49999"
      - "50000-50050:50000-50050/udp"
